package com.products.backend.domain.validators;

public enum CodigoErrorEnum {

    ERROR_CREANDO_COPIA_ARCHIVO, ERROR_ELIMINANDO_ARCHIVO, ERROR_CONVIRTIENDO_OBJ_A_JSON,
    INFRA_ERROR_CONEXION_BD, UNAUTHORIZED, FORBIDDEN, TIPO_NODE_INCORRECTO, INFRA_ERROR_CONSUMIENDO_SERVICIO_HTTP,
    ESTADO_INCORRECTO_PARA_OPERACION, TIPO_REGISTRO_INCORRECTO, OPERACION_NO_SOPORTADA, ERROR_CONVIRTIENDO_JSON_A_OBJ, PLATAFORMA_REQUERIDA, CUENTA_REQUERIDA,
    ERROR_CONFIGURACION, CAMPO_REQUERIDO, ERROR_INTEGRIDAD_DATOS, SERVICIOS_LIQUIDAR_NO_ENCONTRADOS, ERROR_COMBINACION_SUCURSALES_LIQUIDACION,
    ERROR_SERVICIO_LIQUIDADO_NO_ANULABLE, ERROR_SERVICIO_ANULADO_NO_ANULABLE, DATOS_CENTRALIZACION_NO_ENCONTRADOS
}
